const app=document.querySelector('#app');
const STORAGE_KEY='birthday-game-24ppl-v1';
const state={data:null,screen:'start',completed:new Set(),viewed:{},heard:new Set(),voiceAvailable:{},activeVoiceChapter:1,playing:null,audio:null,game:null,pageEntering:true,renderedScreen:null,preloadedImages:[]};
let transitionTimer=null,endingTimers=[],endingRun=0,endingPhase='idle';

const allPeople=()=>state.data.chapters.flatMap(c=>c.people);
const totalPeople=()=>allPeople().length;
const chapter=id=>state.data.chapters.find(c=>c.id===id);
const completedPeople=()=>state.data.chapters.filter(c=>state.completed.has(c.id)).reduce((n,c)=>n+c.people.length,0);
const voiceUnlocked=()=>state.completed.size===state.data.chapters.length;
const shuffle=items=>[...items].sort(()=>Math.random()-.5);
const esc=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function initials(p){const s=String(p.name||p.id||'?').trim();return /^[\x00-\x7F]+$/.test(s)?s.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase():s.slice(0,1);}
function avatar(p,extra=''){return `<span class="avatar-shell ${extra}"><img class="avatar-img" src="${encodeURI(p.avatar)}" alt="${esc(p.name)}的头像" loading="eager" decoding="async"><span class="avatar-fallback">${esc(initials(p))}</span></span>`;}

function loadProgress(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');state.completed=new Set(s.completed||[]);state.viewed=s.viewed||{};state.heard=new Set(s.heard||[]);}catch(_){}}
function saveProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify({completed:[...state.completed],viewed:state.viewed,heard:[...state.heard]}));}
function preloadImages(){const urls=[...new Set(allPeople().flatMap(p=>[p.avatar,p.riddleImage,p.image].filter(Boolean)))];state.preloadedImages=urls.map(url=>{const image=new Image();image.src=encodeURI(url);return image;});}
async function checkVoices(){await Promise.all(allPeople().map(async p=>{if(!p.voice)return state.voiceAvailable[p.id]=false;try{const r=await fetch(encodeURI(p.voice),{method:'HEAD'});state.voiceAvailable[p.id]=r.ok;}catch(_){state.voiceAvailable[p.id]=false;}}));if(state.screen==='voices')render();}

function shell(content,{back=null}={}){return `<div class="shell${state.pageEntering?' page-enter':''}"><header class="topbar">${back?`<button class="back" data-action="${back}">← 返回</button>`:'<span class="brand">BIRTHDAY PROJECT</span>'}<span class="progress">${completedPeople()} / ${totalPeople()} 已认出</span></header>${content}</div>`;}
function syncAttributes(a,b){for(const x of [...a.attributes])if(!b.hasAttribute(x.name))a.removeAttribute(x.name);for(const x of [...b.attributes])if(a.getAttribute(x.name)!==x.value)a.setAttribute(x.name,x.value);if(a instanceof HTMLInputElement&&document.activeElement!==a)a.value=b.value;}
function patchNode(a,b){if(!a||!b||a.nodeType!==b.nodeType||a.nodeName!==b.nodeName){a?.replaceWith(b.cloneNode(true));return;}if(a.nodeType===Node.TEXT_NODE){if(a.nodeValue!==b.nodeValue)a.nodeValue=b.nodeValue;return;}syncAttributes(a,b);const ac=[...a.childNodes],bc=[...b.childNodes],n=Math.min(ac.length,bc.length);for(let i=0;i<n;i++)patchNode(ac[i],bc[i]);for(let i=ac.length-1;i>=bc.length;i--)ac[i].remove();for(let i=n;i<bc.length;i++)a.appendChild(bc[i].cloneNode(true));}
function updateScreen(markup,replace){if(replace||!app.firstElementChild){app.innerHTML=markup;return;}const t=document.createElement('template');t.innerHTML=markup.trim();patchNode(app.firstElementChild,t.content.firstElementChild);}
function render(){const screens={start:renderStart,select:renderSelect,game:renderGame,messages:renderMessages,voices:renderVoices,ending:renderEnding},changed=state.screen!==state.renderedScreen;state.pageEntering=changed;updateScreen(screens[state.screen](),changed);state.renderedScreen=state.screen;if(changed&&state.screen==='ending')requestAnimationFrame(startEndingAnimation);}
function clearEnding(){endingRun++;endingTimers.forEach(clearTimeout);endingTimers=[];document.querySelectorAll('.ending-avatar').forEach(n=>n.getAnimations().forEach(a=>a.cancel()));}
function navigate(screen){clearTimeout(transitionTimer);if(state.screen==='ending')clearEnding();stopAudio();state.screen=screen;render();}

function renderStart(){return `<div class="intro-screen${state.pageEntering?' page-enter':''}" id="intro"><div class="intro-atmosphere"></div><section class="intro-story"><div class="intro-light" aria-hidden="true"><i></i></div><div class="intro-copy"><p class="intro-line one">今天，有一些人留下了一些线索。</p><p class="intro-line two">顺着这点微光，去找到他们吧。</p></div><button class="intro-start" data-action="begin-story">开始寻找</button></section></div>`;}
function renderSelect(){const labels=['短句双向配对','关键词归位','谐音轻解谜','代表图翻牌'];const cards=state.data.chapters.map((c,i)=>{const done=state.completed.has(c.id);return `<button class="chapter-card ${done?'done':''}" data-chapter="${c.id}"><span class="number">CHAPTER 0${c.id}</span>${done?'<span class="status">✓ 已完成</span>':''}<h3>${esc(c.title)}</h3><p>${labels[i]} · ${c.people.length} 位朋友</p></button>`;}).join('');return shell(`<section class="section-head"><p class="eyebrow">Chapter Select</p><h2>从哪里开始？</h2><p>章节可以自由选择，完成状态会保存在这台设备上。</p></section><div class="chapter-grid">${cards}</div><div class="voice-unlock ${voiceUnlocked()?'ready':''}"><strong>${voiceUnlocked()?'声音祝福已解锁':'声音祝福尚未解锁'}</strong><br><span>${voiceUnlocked()?`${totalPeople()} 位朋友已经全部找到。`:`完成四章后解锁 · ${completedPeople()} / ${totalPeople()}`}</span>${voiceUnlocked()?'<div class="actions"><button class="primary" data-action="go-voices">进入 Voice Chapters</button></div>':''}</div><div class="reset-zone"><button class="reset-button" data-action="reset-progress">↻ 重置全部章节</button><p>清除本机保存的通关、寄语和播放状态。</p></div>`,{back:'go-start'});}
function resetProgress(){if(!confirm('确定重置全部章节吗？当前通关记录和已读状态都会清除。'))return;localStorage.removeItem(STORAGE_KEY);state.completed=new Set();state.viewed={};state.heard=new Set();state.activeVoiceChapter=1;state.game=null;navigate('start');}

function beginChapter(id){const c=chapter(id),g={chapterId:id,feedback:'',tone:'',matched:new Set()};if(id===1)Object.assign(g,{people:shuffle(c.people),sentences:shuffle(c.people),selectedPerson:null,selectedSentence:null});if(id===2)Object.assign(g,{keywords:shuffle(c.people.flatMap(p=>p.keywords.map(keyword=>({keyword,personId:p.id})))),placed:{},selectedKeyword:null});if(id===3)Object.assign(g,{index:0,hint:false,reveal:false});if(id===4)Object.assign(g,{images:shuffle(c.people),cards:shuffle(c.people),selectedImage:null,revealed:null,wrongCounts:{},hintPerson:null,busy:false});state.game=g;navigate('game');}
const gameHeader=(c,text)=>`<section class="section-head"><p class="eyebrow">Chapter 0${c.id}</p><h2>${esc(c.title)}</h2><p>${text}</p></section>`;
const feedback=()=>`<p class="toast ${state.game.tone}">${esc(state.game.feedback||'可以慢慢试，没有失败和扣分。')}</p>`;
function renderGame(){const c=chapter(state.game.chapterId);return shell(c.id===1?renderC1(c):c.id===2?renderC2(c):c.id===3?renderC3(c):renderC4(c),{back:'go-select'});}

function renderC1(c){const g=state.game,people=g.people.map(p=>`<button class="person-card ${g.selectedPerson===p.id?'selected':''} ${g.matched.has(p.id)?'matched':''}" data-c1-person="${p.id}" ${g.matched.has(p.id)?'disabled':''}>${avatar(p)}<strong>${esc(p.name)}</strong></button>`).join(''),sentences=g.sentences.map(p=>`<button class="sentence-card ${g.selectedSentence===p.id?'selected':''} ${g.matched.has(p.id)?'matched':''}" data-c1-sentence="${p.id}" ${g.matched.has(p.id)?'disabled':''}>“${esc(p.sentence)}”</button>`).join('');return gameHeader(c,'可以先点人物，也可以先点短句。选择两端后立即判断。')+`<div class="game-grid people-six">${people}</div><p class="subhead">打乱的短句</p><div class="sentence-list">${sentences}</div>${feedback()}`;}
function tryC1(){const g=state.game,c=chapter(1);if(!g.selectedPerson||!g.selectedSentence)return render();if(g.selectedPerson===g.selectedSentence){g.matched.add(g.selectedPerson);g.feedback='找到一位！这句话确实属于 TA。';g.tone='good';g.selectedPerson=g.selectedSentence=null;if(g.matched.size===c.people.length)return finishChapter(1);}else{g.feedback='再试试，好像不是 TA。';g.tone='bad';g.selectedPerson=g.selectedSentence=null;}render();}

function renderC2(c){const g=state.game,people=c.people.map(p=>{const placed=g.placed[p.id]||[],slots=p.keywords.map((_,i)=>`<span class="slot ${placed[i]?'filled':''}">${esc(placed[i]||'待归位')}</span>`).join('');return `<button class="person-card" data-c2-person="${p.id}">${avatar(p)}<strong>${esc(p.name)}</strong><span class="slots">${slots}</span></button>`;}).join(''),bank=g.keywords.filter(k=>!g.matched.has(`${k.personId}:${k.keyword}`)).map(k=>{const key=`${k.personId}:${k.keyword}`;return `<button class="keyword ${g.selectedKeyword===key?'selected':''}" data-c2-key="${esc(key)}">${esc(k.keyword)}</button>`;}).join('');return gameHeader(c,'先选择一个词条，再点你认为对应的人物。')+`<div class="game-grid people-six">${people}</div><p class="subhead">待归位词条</p><div class="keyword-bank">${bank}</div>${feedback()}`;}
function placeKeyword(id){const g=state.game,c=chapter(2);if(!g.selectedKeyword){g.feedback='请先选择一个词条。';g.tone='';return render();}const [owner,...parts]=g.selectedKeyword.split(':'),keyword=parts.join(':');if(owner===id){g.matched.add(g.selectedKeyword);(g.placed[id]||=[]).push(keyword);g.feedback='归位成功！';g.tone='good';g.selectedKeyword=null;if(g.matched.size===c.people.reduce((n,p)=>n+p.keywords.length,0))return finishChapter(2);}else{g.feedback='这个词有主人，但不是 TA。';g.tone='bad';g.selectedKeyword=null;}render();}

const normalize=s=>String(s).toLowerCase().trim().replace(/\s+/g,'');
function renderC3(c){const g=state.game,p=c.people[g.index];return gameHeader(c,'输入你想到的答案；答错可以继续尝试，也可以使用提示。')+`<div class="riddle"><div class="riddle-index">第 ${g.index+1} / ${c.people.length} 题</div><div class="riddle-text"><img class="riddle-image clue-img" src="${encodeURI(p.riddleImage)}" alt="第 ${g.index+1}题线索图"><span class="asset-fallback">线索图片暂时无法显示</span></div><input class="answer-input" id="answer" autocomplete="off" placeholder="输入昵称或拼音" aria-label="答案"><div class="actions"><button class="primary" data-action="submit-answer">确认答案</button><button class="secondary" data-action="show-hint">提示</button><button class="secondary" data-action="reveal-answer">偷看答案</button></div>${g.hint?`<p class="hint-box">提示：${esc(p.hint)}</p>`:''}${g.reveal?`<p class="hint-box">答案是：<strong class="gold">${esc(p.name)}</strong>。现在可以直接继续。</p><div class="actions"><button class="primary" data-action="accept-reveal">揭晓 TA</button></div>`:''}</div>${feedback()}`;}
function submitAnswer(){const c=chapter(3),g=state.game,p=c.people[g.index],value=document.querySelector('#answer')?.value||'';if(p.answers.some(a=>normalize(a)===normalize(value))){g.feedback=`答对了，是 ${p.name}！`;g.tone='good';return nextRiddle();}g.feedback='很接近也没关系，再想想看。';g.tone='bad';render();}
function nextRiddle(){const c=chapter(3),g=state.game;if(g.index===c.people.length-1)return finishChapter(3);g.index++;g.hint=false;g.reveal=false;render();}

function renderC4(c){const g=state.game,images=g.images.map(p=>`<button class="image-card ${g.selectedImage===p.id?'selected':''} ${g.matched.has(p.id)?'matched':''}" data-c4-image="${p.id}" ${g.matched.has(p.id)||g.busy?'disabled':''}><img class="clue-img" src="${encodeURI(p.image)}" alt="${esc(p.name)}的代表图片"><span class="asset-fallback">代表图暂时无法显示</span><div class="image-label">选择这张代表图</div></button>`).join(''),cards=g.cards.map(p=>{const shown=g.revealed===p.id||g.matched.has(p.id);return `<button class="covered-card ${shown?'revealed':''} ${g.matched.has(p.id)?'matched':''} ${g.hintPerson===p.id?'hint':''}" data-c4-person="${p.id}" ${g.matched.has(p.id)||g.busy?'disabled':''}>${shown?`${avatar(p)}<strong>${esc(p.name)}</strong>`:'<span class="cover">✦</span><span>翻开人物牌</span>'}</button>`;}).join('');return gameHeader(c,'先选一张代表图片，再翻开人物牌寻找对应的人。')+`<p class="subhead">代表图片</p><div class="game-grid chapter-four-grid">${images}</div><p class="subhead">盖住的人物牌</p><div class="game-grid chapter-four-grid">${cards}</div>${feedback()}`;}
function flipPerson(id){const g=state.game,c=chapter(4);if(g.busy)return;if(!g.selectedImage){g.feedback='请先选择一张代表图片。';g.tone='';return render();}g.busy=true;g.revealed=id;g.hintPerson=null;render();setTimeout(()=>{if(state.screen!=='game'||state.game!==g)return;if(g.selectedImage===id){g.matched.add(id);g.feedback='配对成功！';g.tone='good';g.selectedImage=null;g.revealed=null;g.busy=false;if(g.matched.size===c.people.length)return finishChapter(4);}else{const image=g.selectedImage;g.wrongCounts[image]=(g.wrongCounts[image]||0)+1;g.feedback='这张牌不是答案，它会重新盖回。';g.tone='bad';g.revealed=null;g.busy=false;if(g.wrongCounts[image]>=2){g.hintPerson=image;g.feedback='给你一点提示：有一张人物牌正在发光。';}}render();},650);}

function finishChapter(id){state.completed.add(id);saveProgress();state.game={chapterId:id,activeMessage:null};navigate('messages');}
function renderMessages(){const c=chapter(state.game.chapterId),cards=c.people.map(p=>`<article class="message-card"><div class="message-person">${avatar(p)}<strong>${esc(p.name)}</strong></div><p class="message-body">${esc(p.message)}</p></article>`).join('');return shell(`<section class="section-head"><p class="eyebrow">Chapter 0${c.id} Complete</p><h2>你找到他们了</h2><p>他们留下的祝福，都在这里。</p></section><div class="message-grid message-six">${cards}</div><div class="actions"><button class="primary" data-action="go-select">返回章节选择 · ${completedPeople()} / ${totalPeople()}</button></div>`);}

function renderVoices(){const c=chapter(state.activeVoiceChapter),tabs=state.data.chapters.map(x=>`<button class="chip ${x.id===c.id?'active':''}" data-voice-chapter="${x.id}">Voice 0${x.id}</button>`).join(''),cards=c.people.map(p=>{const available=state.voiceAvailable[p.id]===true;return `<button class="voice-card ${state.playing===p.id?'playing':''}" ${available?`data-voice-person="${p.id}"`:'disabled'}>${avatar(p)}<strong>${esc(p.name)}</strong><div class="voice-state">${available?(state.playing===p.id?'▮▮ 正在播放 · 点击暂停':state.heard.has(p.id)?'✓ 已听过 · 再次播放':'▶ 点击播放'):'语音祝福素材待补充'}</div></button>`;}).join('');return shell(`<section class="section-head"><p class="eyebrow">Voice Chapters</p><h2>想亲口告诉你的话</h2><p>语音结构已经按章节保留；当前缺失的素材会显示为待补充。</p></section><div class="chapter-tabs">${tabs}</div><div class="voice-grid voice-six">${cards}</div><div class="voice-placeholder"><strong>语音祝福素材待补充</strong><span>当前开发版可先继续查看完整结尾。</span></div><div class="actions"><button class="primary" data-action="go-ending">继续查看结尾 Demo</button></div>`,{back:'go-select'});}
function stopAudio(){if(state.audio){state.audio.pause();state.audio.currentTime=0;}state.audio=null;state.playing=null;}
function playVoice(id){if(state.voiceAvailable[id]!==true)return;if(state.playing===id){stopAudio();return render();}stopAudio();const p=allPeople().find(x=>x.id===id),audio=new Audio(encodeURI(p.voice));state.audio=audio;state.playing=id;state.heard.add(id);saveProgress();audio.addEventListener('ended',()=>{if(state.audio===audio){state.audio=null;state.playing=null;render();}});audio.addEventListener('error',()=>{if(state.audio===audio){state.voiceAvailable[id]=false;state.audio=null;state.playing=null;render();}});render();audio.play().catch(()=>{if(state.audio===audio){state.audio=null;state.playing=null;render();}});}

function renderEnding(){const people=[...allPeople()].sort((a,b)=>Number(a.id)-Number(b.id)),nodes=people.map(p=>`<div class="ending-avatar" data-person-id="${p.id}" aria-label="${esc(p.id)} ${esc(p.name)}"><i class="avatar-trail"></i>${avatar(p,'ending-orb')}</div>`).join('');return `<div class="ending-screen${state.pageEntering?' page-enter':''}" id="ending"><div class="ending-ambient"></div><figure class="ending-chibi" id="endingChibi"><img src="xiaomi-chibi.webp" alt="小米坐在月亮上的Q版插画"></figure><div class="ending-people">${nodes}</div><p class="ending-blessing">愿这些微小的光，安静地陪你走进新的一年。</p><div class="ending-controls"><button class="ending-link" data-action="go-voices">← 返回声音页</button><button class="ending-link" data-action="replay-ending">↻ Replay Animation</button></div></div>`;}
function heartPoints(count){const s=[];let total=0;for(let i=0;i<=1200;i++){const t=i/1200*Math.PI*2,x=16*Math.sin(t)**3,rawY=-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t)),y=rawY<-5?-5+(rawY+5)*1.38:rawY;if(i){const q=s[i-1];total+=Math.hypot(x-q.x,y-q.y);}s.push({x,y,d:total});}return Array.from({length:count},(_,i)=>{const wanted=i/count*total;let lo=0,hi=s.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(s[mid].d<wanted)lo=mid+1;else hi=mid;}return s[lo];});}
function seed(i,s=0){const x=Math.sin((i+1)*917.13+s*37.17)*43758.5453;return x-Math.floor(x);}
function layoutEnding(){const scene=document.querySelector('#ending'),chibi=document.querySelector('#endingChibi'),nodes=[...document.querySelectorAll('.ending-avatar')];if(!scene||!nodes.length)return;const w=scene.clientWidth,h=scene.clientHeight,count=nodes.length,base=w<520?22:28,heartW=Math.min(w*.91,h*.8,790),heartH=Math.min(h*.55,w*.94,690),scale=Math.min(heartW/32,heartH/29),spacing=106*scale/count,size=Math.max(16,Math.min(base,spacing*.62)),points=heartPoints(count),cs=chibi.offsetWidth,gap=Math.max(27,Math.min(w,h)*.038),px=cs/2+size/2+gap,py=cs/2+size/2+gap,sg=Math.max(7,size*.42),per=Math.max(1,Math.floor((w-30+sg)/(size+sg))),rows=Math.ceil(count/per),bottom=h-Math.max(78,size*2.5);nodes.forEach((n,i)=>{let tx=points[i].x*scale,ty=points[i].y*scale;if(Math.abs(tx)<px&&Math.abs(ty)<py){if(ty<0){tx*=1.7;ty=-py-Math.abs(tx)*.28;}else{const toSide=px-Math.abs(tx),toBottom=py-ty;if(toSide<toBottom)tx=(tx<0?-1:1)*px;else ty=py;}}const row=Math.floor(i/per),start=row*per,num=Math.min(per,count-start),pos=i-start,rowW=num*size+(num-1)*sg,sx=(w-rowW)/2+size/2+pos*(size+sg)-w/2,sy=bottom-(rows-1-row)*(size+sg)-h*.43;n.style.setProperty('--ending-avatar-size',`${size}px`);Object.assign(n.dataset,{sx,sy,tx,ty});n.style.transform=`translate(${endingPhase==='gathered'?tx:sx}px,${endingPhase==='gathered'?ty:sy}px)`;});}
function startEndingAnimation(){clearEnding();const scene=document.querySelector('#ending'),chibi=document.querySelector('#endingChibi'),nodes=[...document.querySelectorAll('.ending-avatar')];if(!scene||!chibi)return;endingPhase='idle';layoutEnding();const token=endingRun,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,start=420,stagger=95,travel=1850;scene.classList.remove('chibi-visible','gathered','heart-pulse');nodes.forEach(n=>n.classList.remove('moving','arrived'));if(reduced){nodes.forEach(n=>{n.style.transform=`translate(${n.dataset.tx}px,${n.dataset.ty}px)`;n.classList.add('arrived');});scene.classList.add('chibi-visible','gathered');endingPhase='gathered';return;}endingPhase='moving';const durations=nodes.map((_,i)=>travel+seed(i,12)*260),reveal=Math.max(...durations.map((d,i)=>i*stagger+d));chibi.style.setProperty('--ending-reveal',`${reveal}ms`);endingTimers.push(setTimeout(()=>{if(token===endingRun)scene.classList.add('chibi-visible');},start));nodes.forEach((node,i)=>{const sx=+node.dataset.sx,sy=+node.dataset.sy,tx=+node.dataset.tx,ty=+node.dataset.ty,dx=tx-sx,dy=ty-sy,len=Math.max(Math.hypot(dx,dy),1),bend=(i%2?1:-1)*Math.min(38,len*.075),cx=sx+dx*.52-dy/len*bend,cy=sy+dy*.52+dx/len*bend;endingTimers.push(setTimeout(()=>{if(token!==endingRun)return;node.classList.add('moving');const a=node.animate([{transform:`translate(${sx}px,${sy}px)`},{transform:`translate(${cx}px,${cy}px)`,offset:.52},{transform:`translate(${tx}px,${ty}px)`}],{duration:durations[i],easing:'cubic-bezier(.3,.03,.18,1)',fill:'forwards'});a.finished.then(()=>{if(token===endingRun){node.style.transform=`translate(${tx}px,${ty}px)`;node.classList.remove('moving');node.classList.add('arrived');}}).catch(()=>{});},start+i*stagger));});endingTimers.push(setTimeout(()=>{if(token!==endingRun)return;endingPhase='gathered';scene.classList.add('gathered','heart-pulse');endingTimers.push(setTimeout(()=>{if(token===endingRun)scene.classList.remove('heart-pulse');},1200));},start+reveal+120));}

app.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const a=el.dataset.action;if(a==='begin-story'){const intro=document.querySelector('#intro');if(intro?.classList.contains('leaving'))return;intro?.classList.add('leaving');el.disabled=true;transitionTimer=setTimeout(()=>navigate('select'),1500);return;}if(a==='go-start')navigate('start');if(a==='go-select')navigate('select');if(a==='go-voices'&&voiceUnlocked())navigate('voices');if(a==='go-ending')navigate('ending');if(a==='replay-ending')startEndingAnimation();if(a==='reset-progress')resetProgress();if(el.dataset.chapter)beginChapter(Number(el.dataset.chapter));if(el.dataset.c1Person){state.game.selectedPerson=el.dataset.c1Person;tryC1();}if(el.dataset.c1Sentence){state.game.selectedSentence=el.dataset.c1Sentence;tryC1();}if(el.dataset.c2Key){state.game.selectedKeyword=el.dataset.c2Key;state.game.feedback='已选择词条，请点击人物。';state.game.tone='';render();}if(el.dataset.c2Person)placeKeyword(el.dataset.c2Person);if(a==='submit-answer')submitAnswer();if(a==='show-hint'){state.game.hint=true;render();}if(a==='reveal-answer'){state.game.reveal=true;render();}if(a==='accept-reveal')nextRiddle();if(el.dataset.c4Image&&!state.game.busy){state.game.selectedImage=el.dataset.c4Image;state.game.feedback='图片已选中，现在翻开一张人物牌。';state.game.tone='';render();}if(el.dataset.c4Person)flipPerson(el.dataset.c4Person);if(el.dataset.message){const id=state.game.chapterId;state.viewed[id]||=[];if(!state.viewed[id].includes(el.dataset.message))state.viewed[id].push(el.dataset.message);state.game.activeMessage=el.dataset.message;saveProgress();render();}if(el.dataset.voiceChapter){stopAudio();state.activeVoiceChapter=Number(el.dataset.voiceChapter);render();}if(el.dataset.voicePerson)playVoice(el.dataset.voicePerson);});
app.addEventListener('error',e=>{const image=e.target;if(!(image instanceof HTMLImageElement))return;console.warn('Asset failed to load:',image.src);if(image.classList.contains('avatar-img'))image.closest('.avatar-shell')?.classList.add('image-error');if(image.classList.contains('clue-img'))image.parentElement?.classList.add('image-error');},{capture:true});
app.addEventListener('keydown',e=>{if(e.key==='Enter'&&state.screen==='game'&&state.game.chapterId===3&&document.activeElement.id==='answer')submitAnswer();});
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.screen==='ending')layoutEnding();},180);});
async function init(){try{const r=await fetch('people_data.json');if(!r.ok)throw new Error('无法读取人物数据');state.data=await r.json();if(!Array.isArray(state.data.chapters)||state.data.chapters.length!==4)throw new Error('人物数据格式不正确');loadProgress();render();preloadImages();checkVoices();}catch(error){app.innerHTML=`<div class="error"><div><h2>试玩版无法启动</h2><p>${esc(error.message)}</p><p>请通过本地服务器或 GitHub Pages 打开。</p></div></div>`;}}
app.innerHTML='<div class="loading">正在准备生日线索…</div>';init();
